### ISSUE TITLE
How does the test find the package?

### ISSUE THREAD

**Issue by davidebbo** [BillMills/python-package-example#1]
Learning Python, and very new to packages. If I clone this repo and run `python3 tests/test.py`, it fails with:

```
    from myPackage import somePython
ModuleNotFoundError: No module named 'myPackage'
```

Is there some setup step that needs to be done first, e.g. to modify the search path? Thanks!

**Comment by katieannemills** [comment]
Hi @davidebbo, thanks for your question:

 - Update `myPackage/__init__.py` to what is now in this repo, per the guide at https://github.com/BillMills/pythonPackageLesson
 - Use a test runner to run your tests: `nosetests tests/test.py`; you may need to install nose first, `pip install nose`.
 - Please note this repo is the better part of a decade old; there are new tools and workflows you'll want to familiarize yourself with if you're releasing packages on Pypi. The repo structure is still valid, but when actually pushing to Pypi, I use [twine](https://twine.readthedocs.io/en/stable/) these days for professional projects.

**Comment by davidebbo** [comment]
Thanks @BillMills ! `nosetests` [blows up](https://forum.learncodethehardway.com/t/ex46-nosetests-error/5683), as it's apparently unsupported in recent Python versions (like 3.9+).

They suggest using `pytest` instead, though that seems to use a different paradigm. Anyway, I'll keep playing with this.
